"""
LangGraph state schema for the Case Intel AI workflow.

Defines the typed state dictionary that flows through every node in the graph.

Changes from original:
  - Added `hyde_passage`: stores the hypothetical document generated by
    hyde_expand and used as the vector search query.
  - `requires_clarification` and `clarification_question` remain in state for
    API compatibility even though the current 3-node graph does not route to a
    dedicated clarification step.
"""

from typing import Any, Optional, TypedDict


class ChunkData(TypedDict):
    """Serialized representation of a retrieved document chunk."""

    chunk_id: int
    document_id: int
    chunk_index: int
    text: str
    score: float
    metadata: dict[str, Any]


class CitationData(TypedDict):
    """A citation linking an answer claim to a source chunk."""

    chunk_id: int
    document_id: int
    citation_text: str
    source_type: str


class AgentState(TypedDict):
    """Full state passed between every node in the LangGraph pipeline."""

    # --- Input ---
    user_query: str
    case_id: Optional[int]
    conversation_id: Optional[int]
    conversation_history: list[dict]   # [{"role": "user"|"assistant", "content": str}]

    # --- HyDE expansion (hyde_expand node) ---
    hyde_passage: str                  # hypothetical doc excerpt used for vector search
    query_type: str                    # simple_qa | summarize | compare | timeline
    requires_clarification: bool
    clarification_question: Optional[str]

    # --- Retrieval (hybrid_search node) ---
    retrieved_chunks: list[ChunkData]
    chunk_count: int
    search_confidence: float           # rerank score of the top result, 0.0–1.0

    # --- Generation (generate_answer node) ---
    answer: str
    answer_confidence: float
    citations: list[CitationData]

    # --- Error handling ---
    error: Optional[str]
