"use client";

import { useEffect, useState } from "react";
import { Loader2, Save } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Skeleton } from "@/components/ui/skeleton";
import { showToast } from "@/components/ui/toaster";
import { APIError } from "@/lib/api/client";
import { useAdvocateProfile, useUpdateAdvocateProfile } from "@/hooks/use-billing";

/** The billing identity that appears on every generated invoice.
 *
 * Until this existed the profile could only be set from a management
 * command, so an invoice generated by a normal user was headed with the
 * literal "Advocate" and a blank address block (see
 * invoice_service.render_invoice_pdf, which falls back to exactly that).
 *
 * Page chrome (wrapper padding/width, heading scale, label style) mirrors
 * cases/new/page.tsx -- the other standalone single-card form page in the
 * app -- rather than the auth pages' .ci-label/font-serif treatment, which
 * is a distinct marketing/login style not used anywhere inside the
 * dashboard shell. */
export default function SettingsPage() {
  const { data: profile, isLoading } = useAdvocateProfile();
  const updateProfile = useUpdateAdvocateProfile();

  const [letterheadName, setLetterheadName] = useState("");
  const [address, setAddress] = useState("");
  const [barNumber, setBarNumber] = useState("");
  const [defaultFee, setDefaultFee] = useState("");
  const [invoicePrefix, setInvoicePrefix] = useState("");

  // Seed the form once the profile lands. Keyed on the profile object so
  // a refetch doesn't stomp edits the user is midway through typing.
  useEffect(() => {
    if (!profile) return;
    setLetterheadName(profile.letterhead_name);
    setAddress(profile.address);
    setBarNumber(profile.bar_registration_number);
    setDefaultFee(profile.default_fee_amount);
    setInvoicePrefix(profile.invoice_prefix);
  }, [profile]);

  async function handleSubmit(event: React.FormEvent) {
    event.preventDefault();
    try {
      await updateProfile.mutateAsync({
        letterhead_name: letterheadName,
        address,
        bar_registration_number: barNumber,
        default_fee_amount: defaultFee,
        invoice_prefix: invoicePrefix,
      });
      showToast.success("Billing profile saved", "New invoices will use these details.");
    } catch (error) {
      const detail =
        error instanceof APIError && error.data && typeof error.data === "object"
          ? Object.values(error.data as Record<string, unknown>).flat().join(" ")
          : null;
      showToast.error("Could not save", detail || "Please check the values and try again.");
    }
  }

  if (isLoading) {
    return (
      <div className="px-4 sm:px-7 pt-5 sm:pt-7 pb-[60px] max-w-[700px] mx-auto">
        <div className="mb-5">
          <Skeleton className="h-8 w-40 mb-1.5" />
          <Skeleton className="h-4 w-72" />
        </div>
        <Skeleton className="h-[420px] rounded-xl" />
      </div>
    );
  }

  return (
    <div className="px-4 sm:px-7 pt-5 sm:pt-7 pb-[60px] max-w-[700px] mx-auto">
      <div className="mb-5">
        <h1 className="text-page-title text-gray-900 mb-1.5">Settings</h1>
        <p className="text-sm text-gray-600">
          Your billing identity — this is what appears on generated invoices.
        </p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Invoice Letterhead</CardTitle>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleSubmit} className="space-y-4">
            <div>
              <label htmlFor="letterhead_name" className="mb-1 block text-sm font-medium text-gray-700">
                Name / Firm
              </label>
              <Input
                id="letterhead_name"
                value={letterheadName}
                onChange={(e) => setLetterheadName(e.target.value)}
                placeholder="e.g. S. Bhagath, Advocate"
              />
              <p className="mt-1 text-xs text-gray-500">
                Shown at the top of every invoice. Left blank, invoices are headed
                &ldquo;Advocate&rdquo;.
              </p>
            </div>

            <div>
              <label htmlFor="address" className="mb-1 block text-sm font-medium text-gray-700">
                Address
              </label>
              <Textarea
                id="address"
                value={address}
                onChange={(e) => setAddress(e.target.value)}
                rows={4}
                placeholder={"12 Court Road\nHyderabad 500001"}
              />
            </div>

            <div>
              <label htmlFor="bar_registration_number" className="mb-1 block text-sm font-medium text-gray-700">
                Bar Registration Number
              </label>
              <Input
                id="bar_registration_number"
                value={barNumber}
                onChange={(e) => setBarNumber(e.target.value)}
                placeholder="e.g. AP/1234/2015"
              />
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label htmlFor="default_fee_amount" className="mb-1 block text-sm font-medium text-gray-700">
                  Default Appearance Fee
                </label>
                <Input
                  id="default_fee_amount"
                  value={defaultFee}
                  onChange={(e) => setDefaultFee(e.target.value)}
                  inputMode="decimal"
                  placeholder="e.g. 15000"
                />
                <p className="mt-1 text-xs text-gray-500">
                  Pre-fills new fees when you don&apos;t type an amount.
                </p>
              </div>
              <div>
                <label htmlFor="invoice_prefix" className="mb-1 block text-sm font-medium text-gray-700">
                  Invoice Prefix
                </label>
                <Input
                  id="invoice_prefix"
                  value={invoicePrefix}
                  onChange={(e) => setInvoicePrefix(e.target.value)}
                  placeholder="INV"
                />
                <p className="mt-1 text-xs text-gray-500">
                  &ldquo;INV&rdquo; numbers invoices INV-0001, INV-0002, …
                </p>
              </div>
            </div>

            {profile && profile.last_invoice_sequence > 0 && (
              <p className="text-xs text-gray-500">
                Last issued: {profile.invoice_prefix}-
                {String(profile.last_invoice_sequence).padStart(4, "0")}. Changing the prefix
                only affects invoices issued from now on — numbers already sent to clients
                keep their original form.
              </p>
            )}

            <Button type="submit" disabled={updateProfile.isPending}>
              {updateProfile.isPending ? (
                <Loader2 className="h-4 w-4 animate-spin" />
              ) : (
                <Save className="h-4 w-4" />
              )}
              {updateProfile.isPending ? "Saving..." : "Save Changes"}
            </Button>
          </form>
        </CardContent>
      </Card>
    </div>
  );
}
