"use client";

import { useEffect, useState } from "react";
import { AlertTriangle, KeyRound, Loader2, Save, ShieldAlert, UserCog } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Skeleton } from "@/components/ui/skeleton";
import { showToast } from "@/components/ui/toaster";
import { APIError } from "@/lib/api/client";
import { changePassword, changeUsername } from "@/lib/api/auth";
import { setToken, setUsername as storeUsername } from "@/lib/auth";
import { useAdvocateProfile, useUpdateAdvocateProfile } from "@/hooks/use-billing";

/** The billing identity that appears on every generated invoice.
 *
 * Until this existed the profile could only be set from a management
 * command, so an invoice generated by a normal user was headed with the
 * literal "Advocate" and a blank address block (see
 * invoice_service.render_invoice_pdf, which falls back to exactly that).
 *
 * Page chrome (wrapper padding/width, heading scale, label style) mirrors
 * cases/new/page.tsx -- the other standalone single-card form page in the
 * app -- rather than the auth pages' .ci-label/font-serif treatment, which
 * is a distinct marketing/login style not used anywhere inside the
 * dashboard shell. */
export default function SettingsPage() {
  const { data: profile, isLoading } = useAdvocateProfile();
  const updateProfile = useUpdateAdvocateProfile();

  const [letterheadName, setLetterheadName] = useState("");
  const [address, setAddress] = useState("");
  const [barNumber, setBarNumber] = useState("");
  const [contactEmail, setContactEmail] = useState("");
  const [defaultFee, setDefaultFee] = useState("");
  const [invoicePrefix, setInvoicePrefix] = useState("");

  // Seed the form once the profile lands. Keyed on the profile object so
  // a refetch doesn't stomp edits the user is midway through typing.
  useEffect(() => {
    if (!profile) return;
    setLetterheadName(profile.letterhead_name);
    setAddress(profile.address);
    setBarNumber(profile.bar_registration_number);
    setContactEmail(profile.contact_email);
    setDefaultFee(profile.default_fee_amount);
    setInvoicePrefix(profile.invoice_prefix);
  }, [profile]);

  async function handleSubmit(event: React.FormEvent) {
    event.preventDefault();
    try {
      await updateProfile.mutateAsync({
        letterhead_name: letterheadName,
        address,
        bar_registration_number: barNumber,
        contact_email: contactEmail,
        default_fee_amount: defaultFee,
        invoice_prefix: invoicePrefix,
      });
      showToast.success("Billing profile saved", "New invoices will use these details.");
    } catch (error) {
      const detail =
        error instanceof APIError && error.data && typeof error.data === "object"
          ? Object.values(error.data as Record<string, unknown>).flat().join(" ")
          : null;
      showToast.error("Could not save", detail || "Please check the values and try again.");
    }
  }

  if (isLoading) {
    return (
      <div className="px-4 sm:px-7 pt-5 sm:pt-7 pb-[60px] max-w-[700px] mx-auto">
        <div className="mb-5">
          <Skeleton className="h-8 w-40 mb-1.5" />
          <Skeleton className="h-4 w-72" />
        </div>
        <Skeleton className="h-[420px] rounded-xl" />
      </div>
    );
  }

  return (
    <div className="px-4 sm:px-7 pt-5 sm:pt-7 pb-[60px] max-w-[700px] mx-auto">
      <div className="mb-5">
        <h1 className="text-page-title text-gray-900 mb-1.5">Settings</h1>
        <p className="text-sm text-gray-600">
          Your billing identity — this is what appears on generated invoices.
        </p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Invoice Letterhead</CardTitle>
        </CardHeader>
        <CardContent>
          {/* noValidate: contact_email uses type="email" for the mobile
              keyboard/autofill hint, but validation errors -- including a
              malformed email -- should surface through the same
              server-round-trip toast every other field here uses, not a
              native browser tooltip that silently blocks submission. */}
          <form onSubmit={handleSubmit} className="space-y-4" noValidate>
            <div>
              <label htmlFor="letterhead_name" className="mb-1 block text-sm font-medium text-gray-700">
                Name / Firm
              </label>
              <Input
                id="letterhead_name"
                value={letterheadName}
                onChange={(e) => setLetterheadName(e.target.value)}
                placeholder="e.g. S. Bhagath, Advocate"
              />
              <p className="mt-1 text-xs text-gray-500">
                Shown at the top of every invoice. Left blank, invoices are headed
                &ldquo;Advocate&rdquo;.
              </p>
            </div>

            <div>
              <label htmlFor="address" className="mb-1 block text-sm font-medium text-gray-700">
                Address
              </label>
              <Textarea
                id="address"
                value={address}
                onChange={(e) => setAddress(e.target.value)}
                rows={4}
                placeholder={"12 Court Road\nHyderabad 500001"}
              />
            </div>

            <div>
              <label htmlFor="bar_registration_number" className="mb-1 block text-sm font-medium text-gray-700">
                Bar Registration Number
              </label>
              <Input
                id="bar_registration_number"
                value={barNumber}
                onChange={(e) => setBarNumber(e.target.value)}
                placeholder="e.g. AP/1234/2015"
              />
            </div>

            <div>
              <label htmlFor="contact_email" className="mb-1 block text-sm font-medium text-gray-700">
                Contact Email
              </label>
              <Input
                id="contact_email"
                type="email"
                value={contactEmail}
                onChange={(e) => setContactEmail(e.target.value)}
                placeholder="e.g. advocate@example.com"
              />
              <p className="mt-1 text-xs text-gray-500">
                Your own billing email, not your login email. Client replies to invoices go
                here, and you&apos;re Cc&apos;d on every invoice sent. Leave blank to skip both.
              </p>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label htmlFor="default_fee_amount" className="mb-1 block text-sm font-medium text-gray-700">
                  Default Appearance Fee
                </label>
                <Input
                  id="default_fee_amount"
                  value={defaultFee}
                  onChange={(e) => setDefaultFee(e.target.value)}
                  inputMode="decimal"
                  placeholder="e.g. 15000"
                />
                <p className="mt-1 text-xs text-gray-500">
                  Pre-fills new fees when you don&apos;t type an amount.
                </p>
              </div>
              <div>
                <label htmlFor="invoice_prefix" className="mb-1 block text-sm font-medium text-gray-700">
                  Invoice Prefix
                </label>
                <Input
                  id="invoice_prefix"
                  value={invoicePrefix}
                  onChange={(e) => setInvoicePrefix(e.target.value)}
                  placeholder="INV"
                />
                <p className="mt-1 text-xs text-gray-500">
                  &ldquo;INV&rdquo; numbers invoices INV-0001, INV-0002, …
                </p>
              </div>
            </div>

            {profile && profile.last_invoice_sequence > 0 && (
              <p className="text-xs text-gray-500">
                Last issued: {profile.invoice_prefix}-
                {String(profile.last_invoice_sequence).padStart(4, "0")}. Changing the prefix
                only affects invoices issued from now on — numbers already sent to clients
                keep their original form.
              </p>
            )}

            <Button type="submit" disabled={updateProfile.isPending}>
              {updateProfile.isPending ? (
                <Loader2 className="h-4 w-4 animate-spin" />
              ) : (
                <Save className="h-4 w-4" />
              )}
              {updateProfile.isPending ? "Saving..." : "Save Changes"}
            </Button>
          </form>
        </CardContent>
      </Card>

      <div className="mt-6">
        <ChangeUsernameCard />
      </div>
      <div className="mt-6">
        <ChangePasswordCard />
      </div>
    </div>
  );
}

/** Extracts a human-readable message from an auth-endpoint APIError.
 * Handles the credentials_locked 403 (a fixed { detail, code } shape),
 * ordinary DRF field errors ({ current_password: [...] } etc.), and a
 * network/unknown fallback -- same shape family the rest of the app's
 * auth pages already parse by hand (see app/login/page.tsx), just
 * centralized here since this page has two forms doing it. */
function extractAuthErrorDetail(error: unknown): string {
  if (error instanceof APIError && error.data && typeof error.data === "object") {
    const data = error.data as Record<string, unknown>;
    if (typeof data.detail === "string") {
      return data.detail;
    }
    const firstField = Object.keys(data)[0];
    if (firstField && Array.isArray(data[firstField]) && data[firstField][0]) {
      return String(data[firstField][0]);
    }
  }
  return "Something went wrong. Please try again.";
}

function ChangeUsernameCard() {
  const [currentPassword, setCurrentPassword] = useState("");
  const [newUsername, setNewUsername] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [isLocked, setIsLocked] = useState(false);
  const [isPending, setIsPending] = useState(false);

  const canSubmit = currentPassword.trim().length > 0 && newUsername.trim().length > 0;

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setError(null);
    if (!canSubmit) return;

    setIsPending(true);
    try {
      const result = await changeUsername(currentPassword, newUsername.trim());
      storeUsername(result.username);
      showToast.success("Username changed", `You're now signed in as ${result.username}.`);
      setCurrentPassword("");
      setNewUsername("");
    } catch (err) {
      if (err instanceof APIError && err.data && typeof err.data === "object") {
        const data = err.data as Record<string, unknown>;
        if (data.code === "credentials_locked") setIsLocked(true);
      }
      setError(extractAuthErrorDetail(err));
    } finally {
      setIsPending(false);
    }
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <UserCog className="h-5 w-5 text-gray-500" />
          Change Username
        </CardTitle>
      </CardHeader>
      <CardContent>
        {isLocked ? (
          <LockedNotice />
        ) : (
          <form onSubmit={handleSubmit} className="space-y-4">
            <div>
              <label htmlFor="username_current_password" className="mb-1 block text-sm font-medium text-gray-700">
                Current Password
              </label>
              <Input
                id="username_current_password"
                type="password"
                autoComplete="current-password"
                value={currentPassword}
                onChange={(e) => setCurrentPassword(e.target.value)}
                placeholder="Confirm it's you"
              />
            </div>
            <div>
              <label htmlFor="new_username" className="mb-1 block text-sm font-medium text-gray-700">
                New Username
              </label>
              <Input
                id="new_username"
                autoComplete="username"
                value={newUsername}
                onChange={(e) => setNewUsername(e.target.value)}
                placeholder="e.g. s.bhagath"
              />
            </div>

            {error && (
              <div className="flex items-start gap-2 rounded-lg bg-status-alert-soft p-3 text-sm text-status-alert">
                <AlertTriangle className="h-4 w-4 flex-shrink-0 mt-0.5" />
                <span>{error}</span>
              </div>
            )}

            <Button type="submit" disabled={!canSubmit || isPending}>
              {isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}
              {isPending ? "Saving..." : "Change Username"}
            </Button>
          </form>
        )}
      </CardContent>
    </Card>
  );
}

function ChangePasswordCard() {
  const [currentPassword, setCurrentPassword] = useState("");
  const [newPassword, setNewPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [isLocked, setIsLocked] = useState(false);
  const [isPending, setIsPending] = useState(false);

  const passwordsMatch = newPassword.length === 0 || newPassword === confirmPassword;
  const canSubmit =
    currentPassword.trim().length > 0 &&
    newPassword.length > 0 &&
    newPassword === confirmPassword;

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setError(null);
    if (!canSubmit) return;

    setIsPending(true);
    try {
      const result = await changePassword(currentPassword, newPassword);
      // The server rotated the token on success -- swap to the new one
      // immediately, or this session's very next request 401s.
      setToken(result.token);
      showToast.success("Password changed", "Your password has been updated.");
      setCurrentPassword("");
      setNewPassword("");
      setConfirmPassword("");
    } catch (err) {
      if (err instanceof APIError && err.data && typeof err.data === "object") {
        const data = err.data as Record<string, unknown>;
        if (data.code === "credentials_locked") setIsLocked(true);
      }
      setError(extractAuthErrorDetail(err));
    } finally {
      setIsPending(false);
    }
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <KeyRound className="h-5 w-5 text-gray-500" />
          Change Password
        </CardTitle>
      </CardHeader>
      <CardContent>
        {isLocked ? (
          <LockedNotice />
        ) : (
          <form onSubmit={handleSubmit} className="space-y-4">
            <div>
              <label htmlFor="password_current_password" className="mb-1 block text-sm font-medium text-gray-700">
                Current Password
              </label>
              <Input
                id="password_current_password"
                type="password"
                autoComplete="current-password"
                value={currentPassword}
                onChange={(e) => setCurrentPassword(e.target.value)}
                placeholder="Confirm it's you"
              />
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label htmlFor="new_password" className="mb-1 block text-sm font-medium text-gray-700">
                  New Password
                </label>
                <Input
                  id="new_password"
                  type="password"
                  autoComplete="new-password"
                  value={newPassword}
                  onChange={(e) => setNewPassword(e.target.value)}
                />
              </div>
              <div>
                <label htmlFor="confirm_new_password" className="mb-1 block text-sm font-medium text-gray-700">
                  Confirm New Password
                </label>
                <Input
                  id="confirm_new_password"
                  type="password"
                  autoComplete="new-password"
                  value={confirmPassword}
                  onChange={(e) => setConfirmPassword(e.target.value)}
                />
                {!passwordsMatch && (
                  <p className="mt-1 text-xs text-status-alert">Passwords don&apos;t match.</p>
                )}
              </div>
            </div>

            {error && (
              <div className="flex items-start gap-2 rounded-lg bg-status-alert-soft p-3 text-sm text-status-alert">
                <AlertTriangle className="h-4 w-4 flex-shrink-0 mt-0.5" />
                <span>{error}</span>
              </div>
            )}

            <Button type="submit" disabled={!canSubmit || isPending}>
              {isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}
              {isPending ? "Saving..." : "Change Password"}
            </Button>
          </form>
        )}
      </CardContent>
    </Card>
  );
}

function LockedNotice() {
  return (
    <div className="flex items-start gap-2.5 rounded-lg bg-status-alert-soft p-3.5 text-sm text-status-alert">
      <ShieldAlert className="h-4.5 w-4.5 flex-shrink-0 mt-0.5" />
      <span>
        This account&apos;s credentials have been locked by an administrator and can&apos;t be
        changed here. Contact your administrator if you believe this is a mistake.
      </span>
    </div>
  );
}
