# Generated by Django 5.2.4 on 2026-03-22 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_activitylog_id_alter_case_id_alter_casetag_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GmailCredential",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_address", models.EmailField(max_length=254, unique=True)),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField()),
                ("token_expiry", models.DateTimeField()),
                (
                    "scope",
                    models.TextField(
                        default="https://www.googleapis.com/auth/gmail.readonly"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "gmail_credentials",
            },
        ),
        migrations.CreateModel(
            name="Hearing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hearing_date", models.DateTimeField()),
                (
                    "hearing_type",
                    models.CharField(
                        choices=[
                            ("preliminary", "Preliminary Hearing"),
                            ("motion", "Motion Hearing"),
                            ("trial", "Trial"),
                            ("appeal", "Appeal"),
                            ("sentencing", "Sentencing"),
                            ("arraignment", "Arraignment"),
                            ("status", "Status Conference"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("judge", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("postponed", "Postponed"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("outcome", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hearings",
                        to="core.case",
                    ),
                ),
            ],
            options={
                "db_table": "hearings",
                "ordering": ["hearing_date"],
            },
        ),
    ]
