# Generated by Django 6.0.3 on 2026-07-02 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_documentchunk_embedding_hnsw_index"),
        ("core", "migration_add_hash_and_tsvector"),
    ]

    operations = []
