# Generated by Django 6.0.3 on 2026-07-15 10:06
# Hand-edited: removed two unrelated pre-existing drift operations that
# makemigrations also detected (a documentchunk GIN index rename and a
# content_hash help_text-only AlterField) -- neither is part of case
# tracking, and this migration is meant to be additive-only for that
# feature. See the case_tracking implementation report for details.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_backfill_conversation_titles"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourtFetchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "fields_changed",
                    models.JSONField(
                        blank=True,
                        help_text="Diff of what changed on this fetch (e.g. {'next_hearing_date': ['2026-07-20', '2026-08-03']}).",
                        null=True,
                    ),
                ),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "court_fetch_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="case",
            name="cnr_number",
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="court_type",
            field=models.CharField(
                blank=True,
                choices=[("district", "District Court"), ("high_court", "High Court")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="fetch_status",
            field=models.CharField(
                choices=[
                    ("never_fetched", "Never Fetched"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                ],
                default="never_fetched",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="last_fetched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="tracking_config",
            field=models.JSONField(
                blank=True,
                help_text="Court hierarchy + case_type/case_number/year used to look this case up on eCourts. Shape depends on court_type: district needs state_code/dist_code/court_complex_code/est_code; high_court needs hc_court_code/state_code/bench_code. Both need case_type/case_number/year.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="tracking_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hearing",
            name="business_date",
            field=models.DateField(
                blank=True,
                help_text="eCourts 'business on date' -- the date the case was last acted on, distinct from hearing_date.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hearing",
            name="purpose",
            field=models.CharField(
                blank=True,
                help_text="eCourts 'purpose of hearing' (e.g. 'CALL WITH IAS', 'FOR DISMISSAL').",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hearing",
            name="source",
            field=models.CharField(
                choices=[("manual", "Manual"), ("ecourts", "eCourts")],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="hearing",
            constraint=models.UniqueConstraint(
                fields=("case", "hearing_date", "source"),
                name="unique_hearing_per_case_date_source",
            ),
        ),
        migrations.AddField(
            model_name="courtfetchlog",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fetch_logs",
                to="core.case",
            ),
        ),
    ]
