# Generated by Django 6.0.3 on 2026-07-15 10:08
#
# Unrelated to case tracking. `migration_add_hash_and_tsvector.py` (an
# earlier, out-of-sequence migration) created the GIN index under the name
# document_chunks_search_vector_gin, but core/models/document_chunk.py has
# declared it as document_chunks_svector_gin since before this branch --
# pre-existing drift, discovered while generating the case-tracking
# migration and split out here so that migration stays additive-only.
# Both operations are metadata-only (index rename, help_text wording) with
# no data impact.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_courtfetchlog_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="documentchunk",
            new_name="document_chunks_svector_gin",
            old_name="document_chunks_search_vector_gin",
        ),
        migrations.AlterField(
            model_name="document",
            name="content_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="SHA-256 hex digest of the uploaded file. Used to skip duplicate processing.",
                max_length=64,
                null=True,
            ),
        ),
    ]
