# Generated by Django 5.1.11 on 2026-07-19 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_courttrackingpreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="ocr_applied",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ProcessingJob",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("progress_current", models.IntegerField(default=0)),
                ("progress_total", models.IntegerField(default=0)),
                ("error", models.TextField(blank=True, default="")),
                ("attempts", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_jobs",
                        to="core.document",
                    ),
                ),
            ],
            options={
                "db_table": "processing_jobs",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="processing__status_ac8e44_idx",
                    )
                ],
            },
        ),
    ]
