# Generated by Django 5.1.11 on 2026-07-20 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_document_ocr_applied_processingjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="processingjob",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="processing_jobs",
                to="core.case",
            ),
        ),
        migrations.AddField(
            model_name="processingjob",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("document", "Document Processing"),
                    ("order_sync", "Court Order Sync"),
                ],
                default="document",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("contract", "Contract"),
                    ("pleading", "Pleading"),
                    ("evidence", "Evidence"),
                    ("correspondence", "Correspondence"),
                    ("brief", "Brief"),
                    ("motion", "Motion"),
                    ("order", "Order"),
                    ("court_order", "Court Order (eCourts)"),
                    ("other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="processingjob",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="processing_jobs",
                to="core.document",
            ),
        ),
        migrations.CreateModel(
            name="CourtOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(max_length=50)),
                ("order_date", models.DateField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("judge", models.CharField(blank=True, default="", max_length=255)),
                (
                    "source",
                    models.CharField(
                        choices=[("ecourts", "eCourts")],
                        default="ecourts",
                        max_length=20,
                    ),
                ),
                ("dedup_key", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="court_orders",
                        to="core.case",
                    ),
                ),
                (
                    "document",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="court_order",
                        to="core.document",
                    ),
                ),
            ],
            options={
                "db_table": "court_orders",
                "ordering": ["-order_date", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("case", "dedup_key"), name="unique_court_order_per_case"
                    )
                ],
            },
        ),
    ]
