# Generated by Django 5.1.11 on 2026-07-22 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_owner_required"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="party_advocate_data",
            field=models.JSONField(
                blank=True,
                help_text="Raw per-party advocate name(s) as returned by eCourts case details, e.g. {'petitioner_advocates': [...], 'respondent_advocates': [...]}. Captured during the full CNR fetch for party-role detection.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="processingjob",
            name="payload",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="processingjob",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("document", "Document Processing"),
                    ("order_sync", "Court Order Sync"),
                    ("advocate_import", "Advocate Case Import"),
                ],
                default="document",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AdvocateSearchPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "court_type",
                    models.CharField(
                        choices=[
                            ("district", "District Court"),
                            ("high_court", "High Court"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "hierarchy_config",
                    models.JSONField(
                        help_text="district: state_code/dist_code/court_complex_code/est_code. high_court: hc_court_code/bench_code."
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "advocate_search_preferences",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner",),
                        name="one_advocate_search_preference_per_user",
                    )
                ],
            },
        ),
    ]
