# Generated by Django 5.1.11 on 2026-07-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_case_party_advocate_data_processingjob_payload_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processingjob",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("document", "Document Processing"),
                    ("order_sync", "Court Order Sync"),
                    ("advocate_import", "Advocate Case Import"),
                    ("advocate_search", "Advocate Search (state-wide fan-out)"),
                ],
                default="document",
                max_length=20,
            ),
        ),
    ]
