# Generated by Django 5.1.11 on 2026-07-25 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_processingjob_job_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="user_party_role",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("petitioner", "Petitioner"),
                    ("respondent", "Respondent"),
                ],
                default="unknown",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ClientContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("primary", "Primary"), ("assistant", "Assistant")],
                        default="primary",
                        max_length=20,
                    ),
                ),
                ("is_billing_contact", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_contacts",
                        to="core.case",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "client_contacts",
                "ordering": ["-is_billing_contact", "name"],
            },
        ),
    ]
