# Generated by Django 5.1.11 on 2026-07-31 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_backfill_title_and_client_contacts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TravelBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_type",
                    models.CharField(
                        choices=[
                            ("travel", "Travel"),
                            ("hotel", "Hotel"),
                            ("other", "Other"),
                        ],
                        default="travel",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("booked", "Booked")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("filename", models.CharField(blank=True, default="", max_length=255)),
                ("file_path", models.CharField(blank=True, default="", max_length=500)),
                ("file_type", models.CharField(blank=True, default="", max_length=20)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hearing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_bookings",
                        to="core.hearing",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "travel_bookings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdvocateProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "letterhead_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Name/firm as it should appear at the top of the invoice.",
                        max_length=255,
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Letterhead address block (free text, multi-line).",
                    ),
                ),
                (
                    "bar_registration_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Bar Council registration number.",
                        max_length=100,
                    ),
                ),
                (
                    "default_fee_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Pre-filled as the appearance fee amount for new hearings.",
                        max_digits=12,
                    ),
                ),
                (
                    "invoice_prefix",
                    models.CharField(
                        blank=True,
                        default="INV",
                        help_text="Prefix for generated invoice numbers, e.g. 'INV' -> INV-0001.",
                        max_length=16,
                    ),
                ),
                (
                    "last_invoice_sequence",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Highest invoice sequence issued to THIS advocate. Never decremented -- a deleted invoice does not free its number.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "advocate_profiles",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner",), name="unique_advocate_profile_per_owner"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AppearanceFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("invoiced", "Invoiced"),
                            ("paid", "Paid"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "invoice_sequence",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "invoice_pdf_path",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("invoiced_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sent_to_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "send_status",
                    models.CharField(
                        choices=[
                            ("not_sent", "Not sent"),
                            ("sent", "Sent"),
                            ("logged", "Logged only (email not configured)"),
                        ],
                        default="not_sent",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hearing",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appearance_fee",
                        to="core.hearing",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "appearance_fees",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("invoice_number", ""), _negated=True),
                        fields=("owner", "invoice_number"),
                        name="unique_invoice_number_per_owner",
                    )
                ],
            },
        ),
    ]
