# Generated by Django 5.1.11 on 2026-07-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_travelbooking_advocateprofile_appearancefee"),
    ]

    operations = [
        migrations.AddField(
            model_name="hearing",
            name="cause_list_checked_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the cause list was last checked for this hearing.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hearing",
            name="cause_list_court_hall",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Court hall the matter is listed in, e.g. '1' from 'COURT NO. 1'.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="hearing",
            name="cause_list_item_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Item/serial number in the cause list, e.g. '3'.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="hearing",
            name="cause_list_source",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Which court's cause list produced this, e.g. 'telangana_hc'.",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="hearing",
            name="cause_list_stage",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Cause-list stage heading, e.g. 'FOR ADMISSION (FRESH MATTERS)'.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="hearing",
            name="cause_list_status",
            field=models.CharField(
                choices=[
                    ("not_checked", "Not checked"),
                    ("not_published", "Not yet listed"),
                    ("listed", "Listed"),
                    ("not_listed", "Not listed"),
                ],
                default="not_checked",
                help_text="Whether this hearing was found in the court's published cause list.",
                max_length=20,
            ),
        ),
    ]
