# Generated by Django 5.1.11 on 2026-07-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_hearing_cause_list_checked_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courtorder",
            name="summary_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="courtorder",
            name="summary_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="courtorder",
            name="summary_is_routine_adjournment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="courtorder",
            name="summary_llm_calls",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="LLM calls spent on this order. 0 for the templated paths.",
            ),
        ),
        migrations.AddField(
            model_name="courtorder",
            name="summary_next_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="courtorder",
            name="summary_next_date_purpose",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="courtorder",
            name="summary_petitioner_directions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="courtorder",
            name="summary_respondent_directions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="courtorder",
            name="summary_route",
            field=models.CharField(
                blank=True,
                choices=[
                    ("unreadable", "Unreadable -- no LLM call"),
                    ("short", "Too short -- no LLM call"),
                    ("routine", "Routine adjournment -- no LLM call"),
                    ("llm", "Sent to the LLM"),
                ],
                default="",
                help_text="Which path this order took -- how many orders reach the LLM.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="courtorder",
            name="summary_status",
            field=models.CharField(
                choices=[
                    ("pending", "Not yet summarised"),
                    ("unreadable", "Unreadable (scanned, no text)"),
                    ("no_directions", "No directions issued"),
                    ("summarized", "Summarised"),
                    ("failed", "Summary failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="courtorder",
            name="summary_what_happened",
            field=models.TextField(blank=True, default=""),
        ),
    ]
