# Generated by Django 5.1.11 on 2026-08-16 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_invitetoken"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="courttrackingpreview",
            name="case",
            field=models.ForeignKey(
                blank=True,
                help_text="Null for a case-less preview: the 'Track by CNR' quick-add flow on the manual case entry page fetches a CNR before any Case row exists yet (see preview_case_creation_from_cnr in core/services/court_tracking.py). Confirming that kind of preview creates the Case itself rather than updating one.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracking_previews",
                to="core.case",
            ),
        ),
        migrations.AddConstraint(
            model_name="case",
            constraint=models.UniqueConstraint(
                fields=("owner", "cnr_number"), name="unique_case_owner_cnr_number"
            ),
        ),
    ]
