# Generated by Django 5.1.11 on 2026-08-17 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_accountlock"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="case_number",
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name="case",
            constraint=models.UniqueConstraint(
                fields=("owner", "case_number"), name="unique_case_owner_case_number"
            ),
        ),
    ]
