# Generated by Django 5.1.15 on 2026-08-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_remove_global_case_number_uniqueness"),
    ]

    operations = [
        migrations.AddField(
            model_name="advocateprofile",
            name="contact_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="The advocate's own billing/contact email -- separate from their login email. Used as Reply-To and Cc on invoice emails sent to clients; left blank, invoices send without either.",
                max_length=254,
            ),
        ),
    ]
