# Generated by Django 5.1.11 on 2026-09-15 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_processing_job_cancel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["due_date", "created_at"]},
        ),
        migrations.AddField(
            model_name="task",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="dedup_key",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="task",
            name="due_date_basis",
            field=models.CharField(
                blank=True,
                choices=[
                    ("explicit_date", "Date stated in the order"),
                    ("relative_to_order", "Counted from the order date"),
                    ("next_hearing_fallback", "No period stated -- next hearing date"),
                    ("limitation_rule", "Computed from a limitation rule"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="kind",
            field=models.CharField(
                choices=[
                    ("manual", "Added by you"),
                    ("order_direction", "Court order direction"),
                    ("limitation", "Limitation deadline"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="needs_review",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="rule_key",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="task",
            name="source_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="core.courtorder",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="source_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="task",
            name="trigger_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="task",
            name="user_modified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["owner", "status", "due_date"],
                name="tasks_owner_status_due_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                condition=models.Q(("dedup_key", ""), _negated=True),
                fields=("owner", "dedup_key"),
                name="unique_task_owner_dedup_key",
            ),
        ),
    ]
