# Generated by Django 5.1.11 on 2026-09-15 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_task_foundation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="processingjob",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("document", "Document Processing"),
                    ("order_sync", "Court Order Sync"),
                    ("advocate_import", "Advocate Case Import"),
                    ("advocate_search", "Advocate Search (state-wide fan-out)"),
                    ("case_briefing", "Case Briefing (hearing prep sheet)"),
                ],
                default="document",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CaseBriefing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ready", "Ready"), ("failed", "Failed")],
                        max_length=20,
                    ),
                ),
                ("input_fingerprint", models.CharField(max_length=64)),
                ("text", models.TextField(blank=True, default="")),
                ("error", models.TextField(blank=True, default="")),
                ("llm_calls", models.PositiveSmallIntegerField(default=0)),
                ("generated_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="briefing",
                        to="core.case",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "case_briefings",
            },
        ),
    ]
