# Generated by Django 5.1.11 on 2026-09-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_case_briefing"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="petitioner_name",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="case",
            name="respondent_name",
            field=models.TextField(blank=True, default=""),
        ),
    ]
