"""New columns on three tables that hold real production rows.

  client_contacts    receive_case_updates, receive_payment_reminders,
                     relation_type, relation_name, age, address
  advocate_profiles  advocate_name, phone, reminder_after_days
  cases              client_id (nullable FK -> clients)

Staged the way CLAUDE.md prescribes, following 0032 exactly, so RDS never
sits under a long ACCESS EXCLUSIVE lock:

  NOT NULL columns   ADD COLUMN (nullable, no default)   catalog-only
                     SET DEFAULT                         keeps old code's
                                                         INSERTs valid in
                                                         the deploy window
                     UPDATE ... backfill
                     ADD CONSTRAINT CHECK (IS NOT NULL) NOT VALID
                     VALIDATE CONSTRAINT                 SHARE UPDATE EXCLUSIVE
                     SET NOT NULL                        reuses the proof
                     DROP CONSTRAINT
  cases.client_id    ADD COLUMN NULL                     catalog-only
                     ADD CONSTRAINT ... FK NOT VALID     no scan
                     VALIDATE CONSTRAINT                 SHARE UPDATE EXCLUSIVE
                     CREATE INDEX CONCURRENTLY           no write lock

`atomic = False` is what makes the staging real (see 0032's docstring): in
one transaction the first ALTER's ACCESS EXCLUSIVE lock would be held to the
end. It is also required for CREATE INDEX CONCURRENTLY, which refuses to run
inside a transaction block.

The defaults are left in place after SET NOT NULL, as in 0032 -- Django
supplies the value itself, so they only ever matter to the old code during
the deploy window.

Constraint and index names are the ones Django itself generates for these
fields (read from `sqlmigrate` of the autogenerated equivalent), so later
migrations that alter these fields find them where Django expects.

Re-runnable: every statement is IF [NOT] EXISTS-guarded, because a
non-atomic migration that fails part-way is not recorded as applied and is
simply run again.
"""

from django.core import validators
import django.db.models.deletion
from django.db import migrations, models


def _staged_not_null(table: str, column: str, sql_type: str, default_sql: str) -> list[str]:
    check = f"{table}_{column}_not_null_chk"
    return [
        f"ALTER TABLE {table} ADD COLUMN IF NOT EXISTS {column} {sql_type}",
        f"ALTER TABLE {table} ALTER COLUMN {column} SET DEFAULT {default_sql}",
        f"UPDATE {table} SET {column} = {default_sql} WHERE {column} IS NULL",
        f"ALTER TABLE {table} DROP CONSTRAINT IF EXISTS {check}",
        f"ALTER TABLE {table} ADD CONSTRAINT {check} CHECK ({column} IS NOT NULL) NOT VALID",
        f"ALTER TABLE {table} VALIDATE CONSTRAINT {check}",
        f"ALTER TABLE {table} ALTER COLUMN {column} SET NOT NULL",
        f"ALTER TABLE {table} DROP CONSTRAINT {check}",
    ]


def _staged_check(table: str, column: str, expression: str) -> list[str]:
    """A PositiveSmallIntegerField's `>= 0` CHECK, added NOT VALID then
    validated. Named the way Postgres names Django's inline column CHECK."""
    name = f"{table}_{column}_check"
    return [
        f"ALTER TABLE {table} DROP CONSTRAINT IF EXISTS {name}",
        f"ALTER TABLE {table} ADD CONSTRAINT {name} CHECK ({expression}) NOT VALID",
        f"ALTER TABLE {table} VALIDATE CONSTRAINT {name}",
    ]


CONTACT_SQL = [
    *_staged_not_null("client_contacts", "receive_case_updates", "boolean", "true"),
    *_staged_not_null("client_contacts", "receive_payment_reminders", "boolean", "true"),
    *_staged_not_null("client_contacts", "relation_type", "varchar(5)", "''"),
    *_staged_not_null("client_contacts", "relation_name", "varchar(255)", "''"),
    *_staged_not_null("client_contacts", "address", "text", "''"),
    # Nullable: no NOT NULL staging needed, only its >= 0 CHECK.
    "ALTER TABLE client_contacts ADD COLUMN IF NOT EXISTS age smallint NULL",
    *_staged_check("client_contacts", "age", "age >= 0"),
]
CONTACT_REVERSE_SQL = [
    f"ALTER TABLE client_contacts DROP COLUMN IF EXISTS {column}"
    for column in (
        "receive_case_updates",
        "receive_payment_reminders",
        "relation_type",
        "relation_name",
        "address",
        "age",
    )
]

PROFILE_SQL = [
    *_staged_not_null("advocate_profiles", "advocate_name", "varchar(255)", "''"),
    *_staged_not_null("advocate_profiles", "phone", "varchar(50)", "''"),
    *_staged_not_null("advocate_profiles", "reminder_after_days", "smallint", "15"),
    *_staged_check("advocate_profiles", "reminder_after_days", "reminder_after_days >= 0"),
]
PROFILE_REVERSE_SQL = [
    f"ALTER TABLE advocate_profiles DROP COLUMN IF EXISTS {column}"
    for column in ("advocate_name", "phone", "reminder_after_days")
]

CASE_CLIENT_FK = "cases_client_id_fcf3eac3_fk_clients_id"
CASE_CLIENT_INDEX = "cases_client_id_fcf3eac3"

CASE_CLIENT_SQL = [
    "ALTER TABLE cases ADD COLUMN IF NOT EXISTS client_id bigint NULL",
    f"ALTER TABLE cases DROP CONSTRAINT IF EXISTS {CASE_CLIENT_FK}",
    f"ALTER TABLE cases ADD CONSTRAINT {CASE_CLIENT_FK} FOREIGN KEY (client_id) "
    "REFERENCES clients (id) DEFERRABLE INITIALLY DEFERRED NOT VALID",
    f"ALTER TABLE cases VALIDATE CONSTRAINT {CASE_CLIENT_FK}",
    f"CREATE INDEX CONCURRENTLY IF NOT EXISTS {CASE_CLIENT_INDEX} ON cases (client_id)",
]
CASE_CLIENT_REVERSE_SQL = [
    f"DROP INDEX CONCURRENTLY IF EXISTS {CASE_CLIENT_INDEX}",
    # Dropping the column drops its FK constraint with it.
    "ALTER TABLE cases DROP COLUMN IF EXISTS client_id",
]


class Migration(migrations.Migration):
    # See the module docstring: without this the staging is pointless and
    # CREATE INDEX CONCURRENTLY fails outright.
    atomic = False

    dependencies = [
        ("core", "0033_client_and_messaging"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(sql=CONTACT_SQL, reverse_sql=CONTACT_REVERSE_SQL),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="clientcontact",
                    name="receive_case_updates",
                    field=models.BooleanField(
                        default=True, help_text="Send this contact 'your matter was heard' updates."
                    ),
                ),
                migrations.AddField(
                    model_name="clientcontact",
                    name="receive_payment_reminders",
                    field=models.BooleanField(
                        default=True, help_text="Send this contact reminders about unpaid invoices."
                    ),
                ),
                migrations.AddField(
                    model_name="clientcontact",
                    name="relation_type",
                    field=models.CharField(
                        blank=True,
                        choices=[
                            ("", "Not set"),
                            ("s/o", "S/o"),
                            ("d/o", "D/o"),
                            ("w/o", "W/o"),
                            ("c/o", "C/o"),
                        ],
                        default="",
                        max_length=5,
                    ),
                ),
                migrations.AddField(
                    model_name="clientcontact",
                    name="relation_name",
                    field=models.CharField(
                        blank=True, default="", help_text="Father's / husband's name.", max_length=255
                    ),
                ),
                migrations.AddField(
                    model_name="clientcontact",
                    name="age",
                    field=models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name="clientcontact",
                    name="address",
                    field=models.TextField(blank=True, default=""),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(sql=PROFILE_SQL, reverse_sql=PROFILE_REVERSE_SQL),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="advocateprofile",
                    name="advocate_name",
                    field=models.CharField(blank=True, default="", max_length=255),
                ),
                migrations.AddField(
                    model_name="advocateprofile",
                    name="phone",
                    field=models.CharField(blank=True, default="", max_length=50),
                ),
                migrations.AddField(
                    model_name="advocateprofile",
                    name="reminder_after_days",
                    field=models.PositiveSmallIntegerField(
                        default=15,
                        help_text=(
                            "Days an invoice may stay unpaid before a payment-reminder draft "
                            "is prepared, and the gap between reminders (at most 3)."
                        ),
                        validators=[
                            validators.MinValueValidator(1),
                            validators.MaxValueValidator(90),
                        ],
                    ),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(sql=CASE_CLIENT_SQL, reverse_sql=CASE_CLIENT_REVERSE_SQL),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="case",
                    name="client",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cases",
                        to="core.client",
                    ),
                ),
            ],
        ),
    ]
