# Generated by Django 5.1.11 on 2026-09-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_contact_profile_case_client_columns"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientmessage",
            name="event_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="courtorder",
            name="disposes_case",
            field=models.BooleanField(default=False),
        ),
    ]
