# Generated by Django 5.1.11 on 2026-09-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_dedupe_court_orders"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="case_number_raw",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
