# Generated by Django 5.1.11 on 2026-09-24 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_normalize_case_numbers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthSession",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("key_hash", models.CharField(max_length=64, unique=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("login", "Signed in"),
                            ("register", "Account created"),
                            ("password_change", "Password changed"),
                            ("legacy", "Carried over from the old sign-in"),
                            ("command", "Created by a management command"),
                        ],
                        default="login",
                        max_length=20,
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "auth_sessions",
                "ordering": ["-last_used_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "revoked_at", "expires_at"],
                        name="auth_sessio_user_id_3e0839_idx",
                    )
                ],
            },
        ),
    ]
