# Generated by Django 5.1.11 on 2026-09-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_carry_over_auth_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="courtorder",
            name="summary_plain",
            field=models.TextField(blank=True, default=""),
        ),
    ]
