"use client";

import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { format, parseISO } from "date-fns";
import { AlertTriangle, FileText, Gavel, Loader2 } from "lucide-react";
import type { CourtOrder, OrderSummary } from "@/types";

interface OrderOverviewProps {
  orders: CourtOrder[];
  onViewOrder?: (orderId: number) => void;
  viewingOrderId?: number;
}

/** Pick the order whose overview belongs at the top of the case page:
 * the most recent DATED one. Undated orders can't be sequenced, so they
 * never win the slot. */
function latestOrder(orders: CourtOrder[]): CourtOrder | null {
  const dated = orders.filter((o) => o.order_date);
  if (dated.length === 0) return null;
  return dated.reduce((newest, candidate) =>
    (candidate.order_date ?? "") > (newest.order_date ?? "") ? candidate : newest,
  );
}

/** The AI summary of the most recent order, at the top of the case page.
 *
 * Renders nothing until an order has actually been summarised -- a
 * "pending" card on every case would be noise, since the summary is
 * generated by the background worker and simply isn't there yet on a
 * freshly-ingested order. */
export function OrderOverviewCard({
  orders,
  onViewOrder,
  viewingOrderId,
}: OrderOverviewProps) {
  const order = latestOrder(orders);
  if (!order) return null;

  const summary = order.summary;
  if (!summary || summary.status === "pending") return null;

  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between flex-wrap gap-2">
        <CardTitle className="flex items-center gap-2">
          <Gavel className="h-4 w-4" />
          Order Overview
          {order.order_date && (
            <span className="text-xs font-normal text-gray-400">
              {format(parseISO(order.order_date), "d MMM yyyy")}
            </span>
          )}
        </CardTitle>
        {order.has_file && (
          <Button
            variant="secondary"
            size="sm"
            onClick={() => onViewOrder?.(order.id)}
            disabled={viewingOrderId === order.id}
          >
            {viewingOrderId === order.id ? (
              <Loader2 className="h-4 w-4 animate-spin" />
            ) : (
              <FileText className="h-4 w-4" />
            )}
            Read the order
          </Button>
        )}
      </CardHeader>
      <CardContent>
        <OrderSummaryBody summary={summary} />
      </CardContent>
    </Card>
  );
}

/** The summary body, shared by the case page and the calendar entry. */
export function OrderSummaryBody({ summary }: { summary: OrderSummary }) {
  if (summary.status === "failed") {
    return (
      <div className="flex items-start gap-2 text-sm text-[#8a5a0b]">
        <AlertTriangle className="h-4 w-4 mt-0.5 flex-shrink-0" />
        <div>
          <div className="font-medium">Summary unavailable</div>
          <div className="text-gray-600 mt-0.5">
            The order could not be summarised automatically. Open the order to
            read it.
          </div>
        </div>
      </div>
    );
  }

  if (summary.status === "unreadable") {
    return (
      <div className="flex items-start gap-2 text-sm text-gray-600">
        <AlertTriangle className="h-4 w-4 mt-0.5 flex-shrink-0 text-gray-400" />
        <span>{summary.what_happened}</span>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      <p className="text-sm text-gray-800">{summary.what_happened}</p>

      {summary.status === "summarized" && (
        <DirectionsBlock summary={summary} />
      )}

      {summary.next_date && (
        <div className="pt-3 border-t border-gray-100 text-sm">
          <span className="text-gray-500">Next date: </span>
          <span className="font-medium text-gray-900">
            {format(parseISO(summary.next_date), "d MMM yyyy")}
          </span>
          {summary.next_date_purpose && (
            <span className="text-gray-500"> — {summary.next_date_purpose}</span>
          )}
        </div>
      )}
    </div>
  );
}

/** Directions, foregrounding the advocate's own side when the case's
 * party role is known.
 *
 * When it's "unknown", both sides are shown neutrally and neither is
 * labelled "yours" -- an advocate acting on the opposing side's
 * obligations is exactly the mistake this must not cause. */
function DirectionsBlock({ summary }: { summary: OrderSummary }) {
  const roleKnown = summary.your_side_directions !== null;

  if (roleKnown) {
    const yours = summary.your_side_directions ?? [];
    const theirs = summary.other_side_directions ?? [];

    return (
      <div className="space-y-3">
        <DirectionsList
          label={summary.your_side_label ?? "Your side"}
          directions={yours}
          emphasis
          emptyText="No directions for your side in this order."
        />
        {theirs.length > 0 && (
          <DirectionsList
            label={summary.other_side_label ?? "Other side"}
            directions={theirs}
          />
        )}
      </div>
    );
  }

  const nothingEither =
    summary.petitioner_directions.length === 0 &&
    summary.respondent_directions.length === 0;
  if (nothingEither) return null;

  return (
    <div className="space-y-3">
      <p className="text-xs text-gray-400">
        Your side isn&apos;t recorded for this case, so both sides are shown as
        the order states them. Set it in Case Overview to see your own
        directions first.
      </p>
      <DirectionsList label="Petitioner" directions={summary.petitioner_directions} />
      <DirectionsList label="Respondent" directions={summary.respondent_directions} />
    </div>
  );
}

interface DirectionsListProps {
  label: string;
  directions: string[];
  emphasis?: boolean;
  emptyText?: string;
}

function DirectionsList({
  label,
  directions,
  emphasis,
  emptyText,
}: DirectionsListProps) {
  if (directions.length === 0 && !emptyText) return null;

  return (
    <div
      className={
        emphasis
          ? "rounded-lg border border-[#dbe3f7] bg-[#f7f9fe] p-3"
          : "rounded-lg border border-gray-100 p-3"
      }
    >
      <div
        className={`text-xs font-semibold uppercase tracking-wide mb-1.5 ${
          emphasis ? "text-[#33449b]" : "text-gray-500"
        }`}
      >
        {label}
      </div>
      {directions.length === 0 ? (
        <div className="text-sm text-gray-500">{emptyText}</div>
      ) : (
        <ul className="space-y-1.5">
          {directions.map((direction, i) => (
            <li key={i} className="text-sm text-gray-800 flex gap-2">
              <span className="text-gray-300 flex-shrink-0">•</span>
              <span>{direction}</span>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
