"""
Django settings for case_intel_project project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    "SECRET_KEY",
    default="django-insecure-9t=v+507ci9+%fmj75n+j4zg7(q1hkp^#_m!-42d!3o@lxjpw0",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='', cast=Csv())


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django.contrib.postgres',
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "django_extensions",
    "django_celery_beat",
    "django_celery_results",
    "core",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "case_intel_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "case_intel_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST"),
        "PORT": config("DB_PORT", cast=int),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Django REST Framework
REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
    ],
    "EXCEPTION_HANDLER": "rest_framework.views.exception_handler",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # Next.js default port
    "http://127.0.0.1:3000",  # Next.js default port
    "http://localhost:8080",  # Alternative frontend port
    "http://127.0.0.1:8080",  # Alternative frontend port
    "https://case-intel.vercel.app",  # Production Vercel deployment
]

# Vercel preview deployments get a fresh URL per build, e.g.
# https://case-intel-<hash>-bhagath-personal-projects.vercel.app
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://case-intel-[a-zA-Z0-9-]+-bhagath-personal-projects\.vercel\.app$",
]

# Auth is via a manually-attached "Authorization: Token ..." header, not
# cookies, so the browser never needs to send credentials cross-origin
# for this app. Keep this False (the stricter setting) unless a future
# feature actually relies on cross-site cookies.
CORS_ALLOW_CREDENTIALS = False

# Additional CORS headers for better API integration
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]


# ============================================================================
# AI Provider Configuration
# ============================================================================

# Embedding provider toggle (Ollama nomic-embed-text is the only supported
# option right now — OpenAI embeddings remain available as a fallback path,
# but Gemini/other embedding providers are deliberately not implemented).
USE_OLLAMA = config("USE_OLLAMA", default=False, cast=bool)

# LLM (chat generation) provider toggle — independent of USE_OLLAMA/embeddings.
# When true, get_llm_client() routes to Groq's OpenAI-compatible endpoint
# instead of Ollama or OpenAI, regardless of the embedding provider in use.
USE_GROQ = config("USE_GROQ", default=False, cast=bool)

# Groq Configuration (used when USE_GROQ=true)
GROQ_API_KEY = config("GROQ_API_KEY", default="")
GROQ_MODEL = config("GROQ_MODEL", default="llama-3.3-70b-versatile")
GROQ_BASE_URL = "https://api.groq.com/openai/v1"

# OpenAI Configuration (used when USE_OLLAMA=false and USE_GROQ=false)
OPENAI_API_KEY = config("OPENAI_API_KEY", default="")
OPENAI_MODEL = config("OPENAI_MODEL", default="gpt-4o")
OPENAI_EMBEDDING_MODEL = config("OPENAI_EMBEDDING_MODEL", default="text-embedding-3-small")

# Ollama Configuration (used when USE_OLLAMA=true)
OLLAMA_BASE_URL = config("OLLAMA_BASE_URL", default="http://localhost:11434")
OLLAMA_MODEL = config("OLLAMA_MODEL", default="llama3.1:8b")
OLLAMA_EMBEDDING_MODEL = config("OLLAMA_EMBEDDING_MODEL", default="nomic-embed-text")

# AI Workflow Configuration
AI_SEARCH_TOP_K = config("AI_SEARCH_TOP_K", default=10, cast=int)
AI_RERANK_TOP_K = config("AI_RERANK_TOP_K", default=5, cast=int)
AI_CONFIDENCE_THRESHOLD = config("AI_CONFIDENCE_THRESHOLD", default=0.5, cast=float)
AI_MAX_CONVERSATION_HISTORY = config("AI_MAX_CONVERSATION_HISTORY", default=5, cast=int)

# Embedding dimensions - DYNAMIC based on provider
# OpenAI text-embedding-3-small: 1536
# Ollama nomic-embed-text: 768
_EMBEDDING_DIMENSIONS_MAP = {
    "text-embedding-3-small": 1536,
    "text-embedding-3-large": 3072,
    "text-embedding-ada-002": 1536,
    "nomic-embed-text": 768,
    "mxbai-embed-large": 1024,
    "all-minilm": 384,
}

if USE_OLLAMA:
    EMBEDDING_DIMENSIONS = _EMBEDDING_DIMENSIONS_MAP.get(OLLAMA_EMBEDDING_MODEL, 768)
else:
    EMBEDDING_DIMENSIONS = _EMBEDDING_DIMENSIONS_MAP.get(OPENAI_EMBEDDING_MODEL, 1536)

# Media files (uploaded documents)
MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

# ============================================================================
# Gmail OAuth Configuration
# ============================================================================
GMAIL_CLIENT_ID = config("GMAIL_CLIENT_ID", default="")
GMAIL_CLIENT_SECRET = config("GMAIL_CLIENT_SECRET", default="")
GMAIL_REDIRECT_URI = config(
    "GMAIL_REDIRECT_URI", default="http://localhost:8000/api/gmail/callback/"
)

# ============================================================================
# Celery Configuration -- DISABLED (dead infrastructure, not just unused)
# ============================================================================
# Verified 2026-07-16: zero .delay(/.apply_async(/@shared_task calls or
# tasks.py files anywhere in core/, no CELERY_BEAT_SCHEDULE. case_intel_project/
# celery.py defines the app + a debug_task and nothing else ever dispatches
# through it. ARCHITECTURE.md independently confirms document processing is
# synchronous. django_celery_beat/django_celery_results stay in INSTALLED_APPS
# (harmless -- just DB-backed models/admin, no live connection) but the
# broker/backend settings that would point Celery at Redis are intentionally
# not defined here. If Celery is ever actually wired up to a task, restore
# CELERY_BROKER_URL / CELERY_RESULT_BACKEND (and provision a Redis instance --
# see PROVISIONING.md) at that point, not before.

# ============================================================================
# Cache Configuration
# ============================================================================
CACHES = {
    'default': {
        # LocMemCache -- Redis was never needed for anything except this
        # cache (Celery is unused, see above). Only two real consumers, both
        # via the plain get/set/incr cache API, nothing Redis-specific:
        #   - core/services/court_data/ecourts_provider.py: court hierarchy
        #     lookups (states/districts/complexes/benches), "changes ~never"
        #     per that file's own comment -- fine to be per-process.
        #   - core/services/court_tracking.py: preview-token cache + preview
        #     rate-limit throttle.
        #
        # CAVEAT -- LocMemCache is per-process, not shared across processes.
        # Fine for `manage.py runserver` (one process) and fine for the
        # hierarchy cache under gunicorn with multiple workers (each worker
        # just rebuilds its own copy, no correctness impact). NOT fine for
        # the preview-token flow if gunicorn ever runs with >1 worker: a
        # preview_case_tracking() call and the confirm_case_tracking() call
        # that follows it can land on different worker processes, and the
        # token won't be visible across them -- confirm would incorrectly
        # raise PreviewExpiredError even though the token hasn't actually
        # expired. Redis (or another shared backend) is required again if
        # this ever runs behind more than one worker process.
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'case-intel-cache',
        'TIMEOUT': 300,  # Default 5 minutes
    }
}

# Logging
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} {levelname} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "core": {
            "handlers": ["console"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
