import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { hearingDigestApi } from "@/lib/api/hearing-digest";

// While the briefing paragraph is being generated by the worker, poll
// until it lands. Generation is one LLM call, so this settles quickly.
const BRIEFING_POLL_MS = 4000;
const BLOB_REVOKE_DELAY_MS = 60_000;

export const hearingDigestKeys = {
  all: ["hearing-digest"] as const,
  detail: (hearingId: number) => [...hearingDigestKeys.all, hearingId] as const,
};

export function useHearingDigest(hearingId: number | null) {
  return useQuery({
    queryKey: hearingDigestKeys.detail(hearingId ?? 0),
    queryFn: () => hearingDigestApi.get(hearingId as number),
    enabled: hearingId !== null,
    refetchInterval: (query) =>
      query.state.data?.briefing.status === "generating" ? BRIEFING_POLL_MS : false,
  });
}

export function useRequestBriefing() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (hearingId: number) => hearingDigestApi.requestBriefing(hearingId),
    onSuccess: (_, hearingId) =>
      queryClient.invalidateQueries({ queryKey: hearingDigestKeys.detail(hearingId) }),
  });
}

/** Downloads the prep sheet PDF under `filename`. */
export function useDownloadDigestPdf() {
  return useMutation({
    mutationFn: async ({ hearingId, filename }: { hearingId: number; filename: string }) => {
      const blob = await hearingDigestApi.fetchPdf(hearingId);
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = filename;
      document.body.appendChild(link);
      link.click();
      link.remove();
      setTimeout(() => URL.revokeObjectURL(url), BLOB_REVOKE_DELAY_MS);
    },
  });
}
